config/routes.rb
Rails.application.routes.draw do
  resources :categories

  resources :posts
  root 'posts#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :category
	mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
      @categories = Category.all

  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @category = Category.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end




  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    if params[:category].blank?
      @posts = Post.all.order("created_at DESC")
    else
       @category_id = Category.find_by(name: params[:category]).id
      @posts = Post.where(category_id: @category_id).order("created_at DESC")
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :category_id, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<div class="max-wide">
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>
</div>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/_footer.html.erb
<section class="footer">
  <div class="container">
    
    <div class="row">
      <div class="col-md-3 col-sm-3">
          <h2>Stay in the know on where to go</h2>
          <h3>Sign up for our e-newsletter</h3>
           <div class="form-group email">
                    <label class="sr-only" for="email">Email</label>
                    <input id="email" type="email" placeholder="johndoe@email.com">
                    </div><!--//form-group-->
                    <button type="submit" class="btn btn-primary">Sign Up</button>
      </div>

      <div class="col-md-3 col-sm-3">
          <h2>Categories</h2>
            <ul>
                <% Category.all.each do |category| %>
                  <li><%= link_to category.name, posts_path(category: category.name) %></li>
                <% end %>
            </ul>
      </div>

      <div class="col-md-3 col-sm-3"> 
          <h2>Social</h2>
          <li><a href="https://www.facebook.com/getbeen" target="_blank">Facebook</a></li>
          <li><a href="http://instagram.com/getbeen/" target="_blank">Instagram</a> </li>
          <li><a href="https://twitter.com/BeenMobileApp" target="_blank">Twitter</a></li>
          <li><a href="http://www.pinterest.com/getbeen" target="_blank">Pinterest</a></li>  
      </div>

      <div class="col-md-3 col-sm-3">
          <h2>About Been</h2>
          <h3>Been is a soon-to-launch mobile app that helps you find places to go based on friends' recommendations and keeps track of where you've been.</h3> 
      </div>

    </div>
  </div>


  <div class="footer-content-container-slim container-semi-opaque">
      <div class="container page-container">
        <div class="row text-muted text-center row-space-8 row-space-top-6 copy-wrap">
          <div id="copyright">© Been 2014</div>
        </div>
      </div>
  </div>

</section>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <ul class="nav navbar-nav">
    <li><%= link_to "Been ", root_path, class: "navbar-brand" %> </li>
  </ul>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Blog |", root_path, class: "navbar-brand" %> </li>
                <% Category.all.each do |category| %>
                <li><%= link_to category.name, posts_path(category: category.name) %></li>
            <% end %>
      
    </ul>
  </div><!-- /.navbar-collapse -->
 </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Been</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	

<%= yield %>

     <div class="push"></div>
   
<%= render 'layouts/footer' %>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %> 
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
    <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %> 
  </div>
    <div class="form-group">
  <%= f.label :category_id %>
  <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "Choose a Category"}, {class: "btn btn-default dropdown-toggle"} %>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container">
	<div class="row" >
		<div class="col-md-12">
 
  	<% @posts.each do |post| %>
  		<div class="posts">
				<div class="box panel panel-default">
						<%= link_to image_tag(post.image.url), post %>  
	      		<h5><%= post.category.name %></h5>
	      		<h6><%= post.title %></h6>
    		</div>
			</div>
		<% end %>


		</div>
	</div>
</div>

app/views/posts/new.html.erb
<div class="max-wide">
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<section class="top">

      <%= image_tag @post.image.url %>
      <h2 class="wide"><%= @post.category.name %></h2>
      <h3 class="wide"><%= @post.title %></h3>


  <div class="max-wide has-padding">
    <p><%= @post.body %></p>
    <%= link_to 'Back', posts_path, class: "btn-primary btn-lg" %>
  </div>




</section>